george Cleartext-Password := "geopwd"
       Reply-Message = "Welcome, George!",
       cisco-avpair = "shell:priv-lvl=15"


testuser Cleartext-Password := "testpassword"
    Reply-Message = "Welcome, Test user",
    cisco-avpair = "shell:priv-lvl=15"


pui Cleartext-Password := "puipwd"
    Reply-Message = "Welcome, Pui!",
    cisco-avpair = "shell:priv-lvl=15"


